### ISSUE TITLE
MILESTONE: 3 user-requested improvements

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#133]
# **2023 SMART Deliverable 3** 

## Loop playback
- [x] https://github.com/simularium/simularium-planning/issues/30

It will be useful to be able to loop playback.

## Save time in URL
- [x] https://github.com/simularium/simularium-planning/issues/113

Saving the time in the URL parameters will allow users to link to a specific time in a trajectory.

## Orthographic camera toggle
- [x] https://github.com/simularium/simularium-planning/issues/149

It's easier to eyeball measurements in 3D with an [orthographic camera view](https://en.wikipedia.org/wiki/Orthographic_projection) rather than the current perspective, so it will be nice to be able to switch between them.
