### ISSUE TITLE
MILESTONE: Next improvements

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#152]
## Capture movies
- [ ] https://github.com/simularium/simularium-planning/issues/22

Saving movies will allow users to embed walkthroughs of trajectories in their presentations and send them to collaborators.

## Show info for selected agent
- [ ] https://github.com/simularium/simularium-planning/issues/18

Seeing info about a selected agent will make it easier to debug or explore a trajectory.

## Set agent color
- [ ] https://github.com/simularium/simularium-planning/issues/28

Users would like to quickly and easily specify custom colors for agents.

## UX research
- [ ] https://github.com/simularium/simularium-planning/issues/143
- [ ] https://github.com/simularium/simularium-planning/issues/144

We want to learn what we should do next to improve users' experience getting started in Simularium, and in using Simularium on mobile devices.

## Generate embed code snippet for viewer
- [ ] https://github.com/simularium/simularium-planning/issues/21

An embed code snippet will allow users to embed simularium viewer windows in their own website.

## More example models: Vivarium and ReaDDy
- [ ] https://github.com/simularium/simularium-planning/issues/102
- [ ] https://github.com/simularium/simularium-planning/issues/90

We will also add more example models to the website.

## UI Polish
- [ ] https://github.com/simularium/simularium-planning/issues/46
- [ ] https://github.com/simularium/simularium-website/issues/304

We will continue to improve the UI.
