### ISSUE TITLE
MILESTONE: More simulation engines

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#167]
- [x] simularium/simulariumio/issues/165
- [ ] simularium/simularium-planning/issues/187
- [x] simularium/simulariumio/issues/166
- [ ] simularium/simulariumio#172
- [ ] simularium/simulariumio#173

## Use Case
As a user of simulation engines not currently supported by Simularium, I would like to be able to import and visualize my data.

## Acceptance Criteria
Add a converter module and an autoconversion template in simulariumio for each new simulator.
