### ISSUE TITLE
MILESTONE: 3 improvements - capture movies, show info, embed code

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#168]
## Capture movies
- [ ] https://github.com/simularium/simularium-planning/issues/22

Saving movies will allow users to embed walkthroughs of trajectories in their presentations and send them to collaborators.

## Show info for selected agent
- [ ] https://github.com/simularium/simularium-planning/issues/18

Seeing info about a selected agent will make it easier to debug or explore a trajectory.

## Generate embed code snippet for viewer
- [ ] https://github.com/simularium/simularium-planning/issues/21

An embed code snippet will allow users to embed simularium viewer windows in their own website.
