### ISSUE TITLE
MILESTONE 8 : Prototype autoconversion, Stream live simulations

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#65]
## Demonstrate autoconversion
- [x] https://github.com/simularium/simularium-planning/issues/45

Autoconversion will remove Python scripting as a barrier to visualizing data from existing simulation engines, which will save users a lot of time and complication. Autoconversion is a large feature, so we will start with a prototype in this milestone. 

## Demonstrate streaming with octopus (Python engine)
- [x] https://github.com/simularium/simularium-planning/issues/51 

The octopus team is working on a prototype for a Python engine to replace the current C++ engine. Our goal is to demonstrate streaming, both from a pre-computed file and then from a live simulation, and test performance of the Python engine in terms of how many concurrent users it can handle.

## More example models, especially with PDB
- [x] https://github.com/simularium/simularium-planning/issues/35

We will also try to convert data for more example models that can be added to the website, especially including PDB to showcase that rendering method.

## User groups & personas
- [x] https://github.com/simularium/simularium-planning/issues/85

**Comment by blairlyons** [comment]
what

**Comment by blairlyons** [comment]
is

**Comment by blairlyons** [comment]
hello

**Comment by jsavieo** [comment]
@blairlyons and @jsavieo move UI polish to milestone 9
