### ISSUE TITLE
MILESTONE 9 : Prep for Autoconversion and Real-time plots, Connect Vivarium

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#66]
## Prep for production autoconversion
- [x] https://github.com/simularium/simularium-planning/issues/64

Autoconversion will remove Python scripting as a barrier to visualizing data from existing simulation engines, which will save users a lot of time and complication. We will finish prototype implementation, templates, and design needed for the production release of autoconversion in the next milestone.

## Initial real-time plots Python library
- [x] https://github.com/simularium/simularium-planning/issues/71

Real time plots will help users explore data interactively, so they can iteratively use the 3D view to ask questions that metrics can help answer, plot the metrics, and repeat.

## Connect octopus to Vivarium
- [x] https://github.com/simularium/octopus/issues/2

We want a prototype Python engine (octopus) that can stream live simulations, and Vivarium can help connect multiple simulation engines.

## More example models
- [x] https://github.com/simularium/simularium-planning/issues/88

We will also try to add more example models to the website.

**Comment by blairlyons** [comment]
hello

**Comment by blairlyons** [comment]
what

**Comment by blairlyons** [comment]
hello
