### ISSUE TITLE
MILESTONE: Autoconversion (production)

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-planning#89]
# **2023 SMART Deliverable 1** 

- [ ] https://github.com/simularium/simularium-website/issues/414
- [x] https://github.com/simularium/simularium-website/issues/295
- [x] https://github.com/simularium/octopus/issues/27
- [x] https://github.com/simularium/simulariumio/issues/118
- [x] https://github.com/simularium/simulariumio/issues/128
- [x] https://github.com/simularium/octopus/issues/18
- [x] https://github.com/simularium/simulariumio/issues/74
- [x] https://github.com/simularium/simulariumio/issues/146
- [x] https://github.com/simularium/simulariumio/issues/145

## Use Case
As a user with data from a supported simulation engine, I want to load a file from the external engine without having to convert in Python first, and instead provide my data through a UI. 

## Acceptance Criteria
- File(s) from any of the simulation engines supported by simulariumio can be loaded locally in the Viewer
- Any additional information needed from the user but not contained in the file(s) can be entered in a UI

## Details
Once the file is provided to the viewer, a UI menu will pop up to gather additional optional (or in some cases, required) information about how to display the file. The file and info from the user is sent to a SimulariumIO module that converts it and returns .simularium data for viewing.
